# Note: These default configs are based on those used in notebooks/yolov3_training.ipynb (Used A100 in Google Colab)
experiment: yolov3_voc           # YOLOv3 model training on Pascal VOC dataset

# Device Configs
device: null                      # If null, run_training.py will use constants.DEVICE

# Base model Configs
base_model:
  backbone_cfgs: ./model_configs/darknet53_backbone.cfg               # Using DarkNet53 backbone
  backbone_weights: ./pretrained_weights/yolov3_416_coco.weights      # Using weights pretrained on MS-COCO
  detector_cfgs: ./model_configs/yolov3_detector_voc.cfg
  input_shape: [1, 3, 416, 416]


# EMA model Configs
ema:
  use_ema: true
  decay: 0.999


# Dataloader Configs
dataloader:
  # scale_anchors, strides, and default_input_size inherited from model
  root: ./data/voc
  dataset_name: voc
  max_imgs: null

  batch_size: 32
  num_workers: 10
  ignore_threshold: 0.5
  min_box_scale: 0.01
  
  multi_augs: [mosaic, mixup]
  multi_aug_prob: 0.85
  mixup_alpha: 2.0
  multiscale_interval: 10
  multiscale_sizes: [320, 352, 384, 416, 448, 480, 512, 544, 576, 608]


# Loss Function Configs
loss_fn:
  # scale_anchors and strides inherited from model
  lambda_coord: 1.5
  lambda_class: 0.3
  lambda_conf: 0.5
  scale_weights: [0.8, 1, 1]      # Scale order: large, medium, small

  use_focal_conf: true            # Uses focal loss for object confidence
  alpha: 0.25
  gamma: 1.0

  softmax_probs: true             # Applies softmax (single-label) to class logits
  class_smoothing: 0.05           # Label smoothing used with softmax and cross-entropy

  use_iou_coord: true             # Uses IoU, GIoU, DIoU, or CIoU for coordinate loss
  iou_coord_reg: ciou


# SGD optimizer Configs
optimizer:
  momentum: 0.9
  lr: 1.0e-3
  weight_decay: 5.0e-4


# Learning Rate Scheduler Configs (Cosine Annealing with Warm-up)
scheduler:
  pre_warmup_lrs: 1.0e-4
  T_max: 180
  warmup_epochs: 5
  eta_min: 1.0e-6
  last_epoch: -1                  # Training from scratch


# Training/Evaluation Configs
train_eval:
  # scale_anchors and strides inherited from model
  num_epochs: 180
  accum_steps: 2                  # Effective batch size is 64
  ema_update_interval: 1

  eval_interval: 5                # Setting to null means no evaluations
  eval_start_epoch: 5

  multi_aug_decay_range: null     # Setting to null means multi-image augmentations never decay off
  obj_threshold: 0.01
  nms_threshold: 0.5
  map_thresholds: [0.5]


# Checkpoint Configs
checkpoint:
  save_dir: ./saved_checkpoints
  checkpoint_name: yolov3_voc_checkpoint.pth
  ignore_exists: false
  resume_path: null
  resume: false                   # Not resuming -> training from scratch